theme : minima
title: Hire Me
author: Daniel Vignoles
email: dvignoles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This site is just proof I can use github-pages

# social links
github_username:  dvignoles

show_excerpts: true # set to false to remove excerpts on the homepage
